name: CI/CD
on:
  push:
    branches:
    - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Deps
      run: |
        echo
        yarn add -D vuepress@next
        yarn add -D @vuepress/plugin-shiki@next
        yarn add -D @vuepress/plugin-google-analytics@next
        yarn add -D vuepress-plugin-md-enhance@next
        yarn add -D vuepress-plugin-sitemap2@next
        yarn add -D vuepress-plugin-seo2@next
        yarn add -D vuepress-plugin-comment2@next
    - name: Build VuePress
      run: yarn docs:build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: www.atri.ml
        path: docs/.vuepress/dist
  deploy:
    needs: build
    runs-on: macos-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: www.atri.ml
        path: dist
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: dist
