name: CI/CD
on:
  push:
    branches:
    - main
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
    - name: setup vuepress next
      run: |
        echo
        pnpm add -D vue vuepress@next @vuepress/client@next @vuepress/utils@next
        pnpm add -D @vuepress/plugin-shiki@next
        pnpm add -D vuepress-plugin-comment2
        pnpm add -D vuepress-plugin-md-enhance
    - name: build vuepress next
      run: pnpm docs:build
    - name: upload package
      uses: actions/upload-artifact@v3
      with:
        name: www.lblb.eu.org
        path: docs/.vuepress/dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: download package
      uses: actions/download-artifact@v3
      with:
        name: www.lblb.eu.org
        path: dist
    - name: deploy to gh-pages
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: dist
