name: CI/CD
on:
  push:
    branches:
    - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: setup vuepress next
      run: |
        echo
        yarn add -D vuepress@next @vuepress/client@next @vuepress/utils@next vue
        yarn add -D @vuepress/plugin-shiki@next
        yarn add -D @vuepress/plugin-google-analytics@next
        yarn add -D vuepress-plugin-md-enhance@next
        yarn add -D vuepress-plugin-sitemap2@next
        yarn add -D vuepress-plugin-seo2@next
        yarn add -D vuepress-plugin-comment2@next
    - name: build vuepress next
      run: yarn docs:build
    - name: upload package
      uses: actions/upload-artifact@v3
      with:
        name: www.atri.ml
        path: docs/.vuepress/dist
  deploy:
    needs: build
    runs-on: macos-latest
    steps:
    - name: download package
      uses: actions/download-artifact@v3
      with:
        name: www.atri.ml
        path: dist
    - name: deploy to gh-pages
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: dist
