name: ghpages-build

on:
  # 在 main 分支被更改时自动运行
  push:
    branches:
      - main
  # 允许手动运行
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  # 预部署 Github Pages
  page:
    runs-on: ubuntu-latest

    steps:
      # 获取储存库源码
      - name: Checkout
        uses: actions/checkout@v3
      # 网站主页文件
      - name: index.html
        working-directory: .github/static
        run: mv ghpage.html index.html
      # 打包网站文件并上传
      - name: Upload to Github Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.github/static'

  # 部署 Github Pages
  deploy:
    runs-on: ubuntu-latest

    # 在 'build' 步骤完成后才进行
    needs: page

    # 环境变量
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 部署 Github Pages
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v2

  # 构建静态资源
  build:
    runs-on: ubuntu-latest

    steps:
      # 获取储存库源码
      - name: Checkout
        uses: actions/checkout@v3
      # 准备 pnpm 环境
      - name: Setup pnpm env
        uses: pnpm/action-setup@v2
        with:
          version: latest
      # 运行先前脚本
      - name: do Shell
        working-directory: src
        run: sh structure.sh
      # 生成静态文件
      - name: Build with VuePress Next
        working-directory: src
        run: pnpm docs:build
      # 打包静态文件并上传
      - name: Upload Static Resource
        uses: actions/upload-artifact@v3
        with:
          name: static-resource
          path: 'src/docs/.vuepress/dist'
