name: gh-pages

on:
  # 在 main 分支被更改时自动运行
  push:
    branches:
      - main
  # 允许手动运行
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:

  # 从 Markdown 构建 HTML
  build:
    runs-on: ubuntu-latest

    steps:
      # 获取储存库源码
      - name: Checkout
        uses: actions/checkout@v3
      # 准备 pnpm 环境
      - name: Setup pnpm env
        uses: pnpm/action-setup@v2
        with:
          version: latest
      # 准备 VuePress Next 环境
      - name: Setup VuePressNext env
        run: |
          echo
          mv docs/.vuepress/package.json .
          pnpm add -D vue vuepress@next @vuepress/client@next @vuepress/utils@next
          pnpm add -D @vuepress/plugin-shiki@next
          pnpm add -D vuepress-plugin-comment2
          pnpm add -D vuepress-plugin-md-enhance
      # 生成静态文件
      - name: Build with VuePressNext
        run: pnpm docs:build
      # 打包静态文件并上传
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
           path: 'docs/.vuepress/dist'

  # 部署 Github Pages
  deploy:
    runs-on: ubuntu-latest

    # 在 'build' 步骤完成后才进行
    needs: build

    # 环境变量
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # 部署 Github Pages
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v2
