name: CI/CD

on:
  push:
    branches:
    - main

jobs:

  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.5.0
    - name: Setup Deps
      run: |
        echo
        yarn add -D vuepress@next
        yarn add -D vuepress-plugin-sitemap2@next
        yarn add -D @vuepress/plugin-shiki@next
        yarn add -D @vuepress/plugin-google-analytics@next
    - name: Build with VuePress
      run: yarn docs:build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: www.atri.ml
        path: docs/.vuepress/dist

  deploy:
    needs: build
    runs-on: macos-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3.0.1
      with:
        name: www.atri.ml
        path: dist
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
        target_branch: gh-pages
        build_dir: dist
